name: Publish from tags
description: 'GitHub Actions: publish from tags for Brick Next repositories'
inputs:
  npm-token:
    description: 'NPM token for publishing'
    required: true
outputs:
  has-tags:
    description: "Whether the HEAD commit has tags"
    value: ${{ steps.check-tags.outputs.has-tags }}
runs:
  using: "composite"
  steps:
  - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/* || echo 'no tags.'
    shell: bash
  
  - name: Check tags
    id: check-tags
    run: |
      echo "::set-output name=has-tags::$(git tag --points-at HEAD)"
    shell: bash

  - name: Lerna Publish
    run: |
      if [[ "_$(git tag --points-at HEAD)" != '_' ]]; then
        npx lerna@6 publish from-git --dist-tag latest --pre-dist-tag next --yes
      else
        echo 'no tags at HEAD.'
      fi
    shell: bash
    env:
      NODE_AUTH_TOKEN: ${{ inputs.npm-token }}
